# permissions for end users to edit greetings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greeting-editor-role
rules:
- apiGroups:
  - hello1.my.domain
  resources:
  - greetings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hello1.my.domain
  resources:
  - greetings/status
  verbs:
  - get
