# permissions for end users to view greetings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greeting-viewer-role
rules:
- apiGroups:
  - hello1.my.domain
  resources:
  - greetings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello1.my.domain
  resources:
  - greetings/status
  verbs:
  - get
